### Variáveis
@baseUrl = http://172.19.0.1:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTliZTMxMS1iYTE0LTdlNzYtYjViZS0yMGI3YTJmOGZlNWMiLCJ0b2tlbiI6ImQxMDNjYmJlLTM3ODktNDA1OS04NGM3LTc0MjQ4OTZkOGYyYSIsImlhdCI6MTc2OTA0Mzc4MywiZXhwIjoxNzY5MDQ0NjgzfQ.r_DFlEcCL2YaLWNvTvRm31MHSIONSVFZTvUPguIYhZg
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTliZTMxMS1iYTE0LTdlNzYtYjViZS0yMGI3YTJmOGZlNWMiLCJ0b2tlbiI6ImQxMDNjYmJlLTM3ODktNDA1OS04NGM3LTc0MjQ4OTZkOGYyYSIsImlhdCI6MTc2OTA0Mzc4MywiZXhwIjoxNzY5MDQ1NTgzfQ.lEd1eJL5z48cjEJkB6SPHIWri0WlrDgxrgjz7qYzj5s

GET {{baseUrl}}/

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "document": "11111111111",
  "password": "admin123"
}


### Refresh token
POST {{baseUrl}}/auth/refresh-token
Authorization: Bearer {{refresh}}

### Buscar dados do usuário autenticado
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}


