### Variáveis
@baseUrl = http://localhost:3333
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTliYjM1OS1kZDY4LTcyMmEtOGEwMi03YWQ3ZDUxNTdmZjkiLCJ0b2tlbiI6ImU0NmJhMGUxLTRlNTctNDkxOS1iY2JjLWZlMDczMDk3ZjY1OCIsImlhdCI6MTc2OTAyNDg1NCwiZXhwIjoxNzY5MDI1NzU0fQ.1DNLuuhmkjWJyQoR9ztvVBY8QNYnHs6SidRrSvRsERk

GET {{baseUrl}}/health

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "document": "11111111111",
  "password": "admin123"
}

### Buscar dados do usuário autenticado
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{token}}